Log Ruby errors on extension download
Log which error caused the download to fail on which mirror. This will
help debugging. Previously it continued without logging the error which
makes debugging more difficult.

The new error in the `install.report` will look like this:

```
---
result:
  status: failed
  message: |-
    Could not download archive from any of our mirrors. Please make sure your network allows access to any of these mirrors.
    Attempted to download the archive from the following urls:
    - URL: https://appsignal-agent-releases.global.ssl.fastly.net/361340a/appsignal-x86_64-darwin-all-static.tar.gz
      Error: Errno::ENOENT: No such file or directory @ rb_sysopen - https://appsignal-agent-releases.global.ssl.fastly.net/361340a/appsignal-x86_64-darwin-all-static.tar.gz
    - URL: https://d135dj0rjqvssy.cloudfront.net/361340a/appsignal-x86_64-darwin-all-static.tar.gz
      Error: Errno::ENOENT: No such file or directory @ rb_sysopen - https://d135dj0rjqvssy.cloudfront.net/361340a/appsignal-x86_64-darwin-all-static.tar.gz
```

(From a Ruby 3.0 install error.)