Disable Rails 4.2 build against Ruby 2.0
It fails now because it can't load a certain Nokogiri class:

```
NameError: uninitialized constant Nokogiri::HTML4
```

I don't care about these old versions which we already don't support for
a while now. Remove it from the CI build.